// assets/underscore/react/src/examples/example-underscore.jsx
/**
 * Example of underscore usage.
 *
 * @export
 * @class ExampleUnderscore
 */
import _ from "underscore";
import React from "react";

export class ExampleUnderscore extends React.Component  {
    /**
     * Creates an instance of ExampleUnderscore.
     */
    constructor(props, context) {
        super(props, context);

        const objA = {name: "bob", car: "porsche"};
        const objB = {name: "bill", age: 40};

        this.state = { result1: JSON.stringify(_.extend(objA, objB)) };
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    render() {
        return <span id="underscore-example">{this.state.result1}</span>;
    }
}

// assets/underscore/angular/src/examples/example-underscore.js
/**
 * Example of underscore usage.
 *
 * @export
 * @class ExampleUnderscore
 */
import _ from "underscore";
import {Component} from "@angular/core";

@Component({
    moduleId: "genModuleId",
    templateUrl: "./example-underscore.html"
})
export class ExampleUnderscore {
    /**
     * Result 1 displayed in the view.
     * @type {string}
     */
    result1;

    /**
     * The component has been initialised.
     * @returns {void}
     */
    ngOnInit() {
        const objA = {name: "bob", car: "porsche"};
        const objB = {name: "bill", age: 40};

        this.result1 = JSON.stringify(_.extend(objA, objB));
    }
}
