// assets/lodash/angular/src/examples/example-lodash.ts
/**
 * Example of lodash usage.
 *
 * @export
 * @class ExampleLodash
 */
import { Component } from "@angular/core";
import /* Synthetic Import */ _ from "lodash";

@Component({
    moduleId: "genModuleId",
    templateUrl: "./example-lodash.html"
})
export class ExampleLodash {
    /**
     * Result 1 displayed in the view.
     * @type {string}
     */
    public result1: string;

    /**
     * The component has been initialised.
     * @returns {void}
     */
    public ngOnInit(): void {
        const objA = { name: "bob", car: "porsche" };
        const objB = { name: "bill", age: 40 };

        this.result1 = JSON.stringify(_.assign(objA, objB));
    }
}

// assets/lodash/react/src/examples/example-lodash.tsx
/**
 * Example of lodash usage.
 *
 * @export
 * @class ExampleLodash
 */
import /* Synthetic Import */ _ from "lodash";
import /* Synthetic Import */ React from "react";

export class ExampleLodash extends React.Component<any, {result1: string}>  {
    /**
     * Creates an instance of ExampleLodash.
     */
    constructor(props?: any, context?: any) {
        super(props, context);

        const objA = { name: "bob", car: "porsche" };
        const objB = { name: "bill", age: 40 };

        this.state = { result1: JSON.stringify(_.assign(objA, objB)) };
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    public render(): JSX.Element {
        return <span id="lodash-example">{this.state.result1}</span>;
    }
}
