// assets/lodash/angular/src/examples/example-lodash.js
/**
 * Example of lodash usage.
 *
 * @export
 * @class ExampleLodash
 */
import _ from "lodash";
import {Component} from "@angular/core";

@Component({
    moduleId: "genModuleId",
    templateUrl: "./example-lodash.html"
})
export class ExampleLodash {
    /**
     * Result 1 displayed in the view.
     * @type {string}
     */
    result1;

    /**
     * The component has been initialised.
     * @returns {void}
     */
    ngOnInit() {
        const objA = {name: "bob", car: "porsche"};
        const objB = {name: "bill", age: 40};

        this.result1 = JSON.stringify(_.assign(objA, objB));
    }
}

// assets/lodash/react/src/examples/example-lodash.jsx
/**
 * Example of lodash usage.
 *
 * @export
 * @class ExampleLodash
 */
import _ from "lodash";
import React from "react";

export class ExampleLodash extends React.Component  {
    /**
     * Creates an instance of ExampleLodash.
     */
    constructor(props, context) {
        super(props, context);

        const objA = {name: "bob", car: "porsche"};
        const objB = {name: "bill", age: 40};

        this.state = { result1: JSON.stringify(_.assign(objA, objB)) };
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    render() {
        return <span id="lodash-example">{this.state.result1}</span>;
    }
}
