// assets/underscore/angular/src/examples/example-underscore.ts
/**
 * Example of underscore usage.
 *
 * @export
 * @class ExampleUnderscore
 */
import { Component } from "@angular/core";
import /* Synthetic Import */ _ from "underscore";

@Component({
    moduleId: "genModuleId",
    templateUrl: "./example-underscore.html"
})
export class ExampleUnderscore {
    /**
     * Result 1 displayed in the view.
     * @type {string}
     */
    public result1: string;

    /**
     * The component has been initialised.
     * @returns {void}
     */
    public ngOnInit(): void {
        const objA = { name: "bob", car: "porsche" };
        const objB = { name: "bill", age: 40 };

        this.result1 = JSON.stringify(_.extend(objA, objB));
    }
}

// assets/underscore/react/src/examples/example-underscore.tsx
/**
 * Example of underscore usage.
 *
 * @export
 * @class ExampleUnderscore
 */
import /* Synthetic Import */ React from "react";
import /* Synthetic Import */ _ from "underscore";

export class ExampleUnderscore extends React.Component<any, {result1: string}>  {
    /**
     * Creates an instance of ExampleUnderscore.
     */
    constructor(props?: any, context?: any) {
        super(props, context);

        const objA = { name: "bob", car: "porsche" };
        const objB = { name: "bill", age: 40 };

        this.state = { result1: JSON.stringify(_.extend(objA, objB)) };
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    public render(): JSX.Element {
        return <span id="underscore-example">{this.state.result1}</span>;
    }
}
